version: "3"
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.16-latest
    volumes:
      - ./config/envoy.yml:/etc/envoy/envoy.yaml
    network_mode: host
  backend:
    build: ./backend
    volumes:
      - ./config/endpoints.txt:/etc/endpoints.txt
    network_mode: host
