version: "3"
services:
  envoy:
    build:
      dockerfile: config/Dockerfile-envoy
    volumes:
      - ./config/envoy.yml:/etc/envoy/envoy.yaml
      - ./config/concurrency.txt:/etc/envoy/concurrency.txt
    network_mode: host
  backend:
    build: ./backend
    volumes:
      - ./config/endpoints.txt:/etc/endpoints.txt
      - ./config.yml:/etc/config.yml
    network_mode: host
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
  grafana:
    image: grafana/grafana
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/provisioning:/etc/grafana/provisioning
      - ./config/dashboards:/var/lib/grafana/dashboards
      - playground-grafana-storage:/var/lib/grafana
    network_mode: host
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    network_mode: host
volumes:
  playground-grafana-storage:
