global:
  scrape_interval: 1s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 127.0.0.1:9090
  - job_name: backend
    static_configs:
      - targets:
        - 127.0.0.1:2112
  - job_name: cadvisor
    static_configs:
      - targets:
        - 127.0.0.1:8080
  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets:
        - 127.0.0.1:9901
